//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInvenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computers_View
    {
        public short asset_id { get; set; }
        public string description { get; set; }
        public string device_type { get; set; }
        public string device_subtype { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string serial_number { get; set; }
        public string building { get; set; }
        public string room { get; set; }
        public string status { get; set; }
        public string host_name { get; set; }
        public string mac_address { get; set; }
        public string static_ip { get; set; }
        public string switch_port { get; set; }
        public Nullable<short> vlan_id { get; set; }
        public string os_version { get; set; }
        public string cpu { get; set; }
        public string ram { get; set; }
        public string hdd { get; set; }
        public string switch_name { get; set; }
    }
}
