//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInvenApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetInventoryEntities : DbContext
    {
        public NetInventoryEntities()
            : base("name=NetInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<computer> computers { get; set; }
        public virtual DbSet<device_types> device_types { get; set; }
        public virtual DbSet<device> devices { get; set; }
        public virtual DbSet<network_devices> network_devices { get; set; }
        public virtual DbSet<virtual_machines> virtual_machines { get; set; }
        public virtual DbSet<vlan> vlans { get; set; }
        public virtual DbSet<wired_devices> wired_devices { get; set; }
        public virtual DbSet<All_Device_Data> All_Device_Data { get; set; }
        public virtual DbSet<Computers_View> Computers_View { get; set; }
        public virtual DbSet<Servers_View> Servers_View { get; set; }
        public virtual DbSet<Switch_Maps> Switch_Maps { get; set; }
        public virtual DbSet<Device_Types_View> Device_Types_View { get; set; }
    }
}
