//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInvenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public short asset_id { get; set; }
        public string description { get; set; }
        public string device_type { get; set; }
        public string device_subtype { get; set; }
        public string manufacturer { get; set; }
        public string model { get; set; }
        public string serial_number { get; set; }
        public string building { get; set; }
        public string room { get; set; }
        public string status { get; set; }
    
        public virtual computer computer { get; set; }
        public virtual device_types device_types { get; set; }
        public virtual network_devices network_devices { get; set; }
        public virtual wired_devices wired_devices { get; set; }
    }
}
