//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetInvenApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class virtual_machines
    {
        public string name { get; set; }
        public string hypervisor { get; set; }
        public string services { get; set; }
        public string os_version { get; set; }
        public string vcpu { get; set; }
        public string ram { get; set; }
        public string hdd { get; set; }
    }
}
